const express = require('express')
const router = express.Router()
const User = require('../models/User')
const Session = require('../models/Session')
const {calculateXP, calculateCoins, calculateLevel} = require('../utils/rewards')